# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160124_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('general', 'General'), ('bug', 'Bug report'), ('suggestion', 'Suggestion')], max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('sender', models.EmailField(max_length=254)),
            ],
        ),
    ]
