# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160203_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(upload_to='/Users/Shubhanker Goyal/mysite/'),
        ),
    ]
