# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20160621_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
